version: 2.1
orbs:
  orb-tools: circleci/orb-tools@12.0
  aws-cli: circleci/aws-cli@4.0
  aws-code-deploy: {}
filters: &filters
  tags:
    only: /.*/
release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
jobs:
  integration-test:
    docker:
      - image: cimg/aws:2023.03
    steps:
      - checkout
      - aws-cli/setup:
          role_arn: "arn:aws:iam::122211685980:role/CPE_CODE_DEPLOY_OIDC_TEST"
          profile_name: OIDC-User
      - run:
          name: Start Instance
          command: aws ec2 start-instances --instance-ids "$AWS_CD_EC2_ID" --region "us-west-1" --profile "OIDC-User"
      - aws-code-deploy/push_bundle:
          region: "us-west-1"
          application_name: CodeDeployOrb_App
          bundle_source: ./sample_app
          bundle_bucket: aws-codedeploy-orb-test
          bundle_key: SampleApp_Linux
          profile_name: OIDC-User
      - aws-code-deploy/deploy_bundle:
          region: "us-west-1"
          application_name: CodeDeployOrb_App
          deployment_group: CodeDeployOrb_App_Group
          bundle_bucket: aws-codedeploy-orb-test
          bundle_key: SampleApp_Linux
          profile_name: OIDC-User
workflows:
  test-deploy:
    jobs:
      - integration-test:
          context: CPE-OIDC
          filters: *filters
      - aws-code-deploy/deploy:
          auth:
            - aws-cli/setup:
                role_arn: arn:aws:iam::122211685980:role/CPE_CODE_DEPLOY_OIDC_TEST
                role_session_name: "Test-session"
                profile_name: "OIDC-User"
          region: "us-west-1"
          profile_name: OIDC-User
          application_name: CodeDeployOrb_App
          deployment_group: CodeDeployOrb_App_Group
          service_role_arn: arn:aws:iam::122211685980:role/CodeDeployServiceRole
          bundle_source: ./sample_app
          bundle_bucket: aws-codedeploy-orb-test
          bundle_key: SampleApp_Linux
          context: CPE-OIDC
          post-steps:
            - run: aws ec2 stop-instances --instance-ids "$AWS_CD_EC2_ID" --region "us-west-1" --profile "OIDC-User"
          requires:
            - integration-test
      - orb-tools/pack:
          filters: *release-filters
      - orb-tools/publish:
          orb_name: circleci/aws-code-deploy
          vcs_type: << pipeline.project.type >>
          pub_type: production
          enable_pr_comment: true
          requires: [ orb-tools/pack, integration-test, aws-code-deploy/deploy ]
          context: orb-publisher
          filters: *release-filters