version: 2.1
orbs:
  aws-code-deploy: circleci/aws-code-deploy@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.6
  aws-cli: circleci/aws-cli@3.1
filters: &filters
  tags:
    only: /.*/
jobs:
  integration-test:
    docker:
      - image: cimg/aws:2023.03
    steps:
      - checkout
      - aws-cli/setup:
          role-arn: "arn:aws:iam::122211685980:role/CPE_CODE_DEPLOY_OIDC_TEST"
          profile-name: OIDC-User
      - run:
          name: Start Instance
          command: aws ec2 start-instances --instance-ids "$AWS_CD_EC2_ID" --region "$AWS_DEFAULT_REGION" --profile "OIDC-User"
      - aws-code-deploy/push-bundle:
          application-name: CodeDeployOrb_App
          bundle-source: ./sample_app
          bundle-bucket: aws-codedeploy-orb-test
          bundle-key: SampleApp_Linux
          profile-name: OIDC-User
      - aws-code-deploy/deploy-bundle:
          application-name: CodeDeployOrb_App
          deployment-group: CodeDeployOrb_App_Group
          bundle-bucket: aws-codedeploy-orb-test
          bundle-key: SampleApp_Linux
          profile-name: OIDC-User
workflows:
  test-deploy:
    jobs:
      - integration-test:
          context: CPE-OIDC
          filters: *filters
      - aws-code-deploy/deploy:
          auth:
            - aws-cli/setup:
                role-arn: arn:aws:iam::122211685980:role/CPE_CODE_DEPLOY_OIDC_TEST
                role-session-name: "Test-session"
                profile-name: "OIDC-User"
          profile-name: OIDC-User
          application-name: CodeDeployOrb_App
          deployment-group: CodeDeployOrb_App_Group
          service-role-arn: arn:aws:iam::122211685980:role/CodeDeployServiceRole
          bundle-source: ./sample_app
          bundle-bucket: aws-codedeploy-orb-test
          bundle-key: SampleApp_Linux
          context: CPE-OIDC
          post-steps:
            - run: aws ec2 stop-instances --instance-ids "$AWS_CD_EC2_ID" --region "$AWS_DEFAULT_REGION" --profile "OIDC-User"
          requires:
            - integration-test
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: circleci/aws-code-deploy
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - integration-test
            - aws-code-deploy/deploy
          context: orb-publisher
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
