description: >
  Creates an application.
parameters:
  application-name:
    description:
      "The name of an AWS CodeDeploy application associated with the applicable IAM user or AWS account."
    type: string
  arguments:
    description: If you wish to pass any additional arguments to the aws deploy command
    type: string
    default: ''
steps:
  - run:
      name: ensure-application-created
      environment:
        ORB_EVAL_APPLICATION_NAME: << parameters.application-name >>
        ORB_VAL_ARGUMENTS: << parameters.arguments >>
      command: << include(scripts/create-application.sh) >>
