# How to author commands: https://circleci.com/docs/2.0/reusing-config/#authoring-reusable-commands
description: >
  Creates an application.
parameters:
  application-name:
    description:
      "The name of an AWS CodeDeploy application associated with the applicable IAM user or AWS account."
    type: string
  arguments:
    description: If you wish to pass any additional arguments to the aws deploy command
    type: string
    default: ''
steps:
  - run:
      name: ensure-application-created
      command: |
        set +e
        aws deploy get-application --application-name << parameters.application-name >><<# parameters.arguments >> << parameters.arguments >><</parameters.arguments >>
        if [ $? -ne 0 ]; then
          set -e
          echo "No application named << parameters.application-name >> found. Trying to create a new one"
          aws deploy create-application --application-name << parameters.application-name >><<# parameters.arguments >> << parameters.arguments >><</parameters.arguments >>
        else
          set -e
          echo "Application named << parameters.application-name >> already exists. Skipping creation."
        fi
