description: >
  Creates an application.
parameters:
  application-name:
    description:
      "The name of an AWS CodeDeploy application associated with the applicable IAM user or AWS account."
    type: string
  arguments:
    description: If you wish to pass any additional arguments to the aws deploy command
    type: string
    default: ''
  profile-name:
    description:
      "The name of an AWS profile to use with aws-cli commands"
    type: string
    default: 'default'
  region:
    type: string
    default: ${AWS_DEFAULT_REGION}
    description: >
      AWS region of CodeDeploy App. Defaults to environment variable ${AWS_DEFAULT_REGION}.
steps:
  - run:
      name: ensure-application-created
      environment:
        ORB_EVAL_APPLICATION_NAME: << parameters.application-name >>
        ORB_VAL_ARGUMENTS: << parameters.arguments >>
        ORB_VAL_PROFILE_NAME: << parameters.profile-name >>
        ORB_EVAL_REGION: << parameters.region >>
      command: << include(scripts/create-application.sh) >>
