description: |
  Creates a deployment group to which application revisions are deployed.
parameters:
  application_name:
    description:
      "The name of an AWS CodeDeploy application associated with the applicable IAM user or AWS account."
    type: string
  deployment_group:
    description:
      "The name of a new deployment group for the specified application."
    type: string
  deployment_config:
    description:
      "Predefined deployment configuration name."
    type: enum
    enum: [ CodeDeployDefault.OneAtATime, CodeDeployDefault.HalfAtATime, CodeDeployDefault.AllAtOnce ]
    default: "CodeDeployDefault.OneAtATime"
  service_role_arn:
    description:
      "The service role for a deployment group."
    type: string
  arguments:
    description: If you wish to pass any additional arguments to the create_deployment_group command
    type: string
    default: ''
  get_deployment_group_arguments
:
    description: If you wish to pass any additional arguments to the get-deployment_group command
    type: string
    default: ''
  profile_name:
    description:
      "The name of an AWS profile to use with aws-cli commands"
    type: string
    default: 'default'
  region:
    type: string
    default: ${AWS_DEFAULT_REGION}
    description: >
      AWS region of CodeDeploy App. Defaults to environment variable ${AWS_DEFAULT_REGION}.
steps:
  - run:
      name: ensure-deployment-created
      environment:
        ORB_EVAL_APPLICATION_NAME: << parameters.application_name >>
        ORB_EVAL_DEPLOYMENT_GROUP: << parameters.deployment_group >>
        ORB_VAL_DEPLOYMENT_CONFIG: << parameters.deployment_config >>
        ORB_EVAL_SERVICE_ROLE_ARN: << parameters.service_role_arn >>
        ORB_EVAL_ARGUMENTS: << parameters.arguments >>
        ORB_EVAL_GET_DEPLOYMENT_GROUP_ARGUMENTS: << parameters.get_deployment_group_arguments
 >>
        ORB_EVAL_PROFILE_NAME: << parameters.profile_name >>
        ORB_EVAL_REGION: << parameters.region >>
      command: << include(scripts/create_deployment_group.sh) >>
