description: >
  Deploy an application to AWS CodeDeploy using static AWS keys for authentication
usage:
  version: 2.1
  orbs:
    aws-code-deploy: circleci/aws-code-deploy@3.0
    # Importing aws-cli orb is required for authentication
    aws-cli: circleci/aws-cli@3.1

  workflows:
    deploy_application:
      jobs:
        - aws-code-deploy/deploy:
            auth:
              # Configure aws credentials with static keys stored as env_vars (AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY)
              - aws-cli/setup
            application-name: myApplication
            deployment-group: myDeploymentGroup
            service-role-arn: myDeploymentGroupRoleARN
            bundle-bucket: myApplicationS3Bucket
            bundle-key: myS3BucketKey
