description: >
  Deploy an application to AWS CodeDeploy
usage:
  version: 2.1
  orbs:
    aws-code-deploy: circleci/aws-code-deploy@3.0
    # import aws-cli orb to install and configure authentication
    aws-cli: circleci/aws-cli@3.1

  workflows:
    deploy_application:
      jobs:
        - aws-code-deploy/deploy:
            pre-steps:
              # install and configure aws credentials with static keys stored as env_vars
              - aws-cli/setup
            application-name: myApplication
            deployment-group: myDeploymentGroup
            service-role-arn: myDeploymentGroupRoleARN
            bundle-bucket: myApplicationS3Bucket
            bundle-key: myS3BucketKey
