description: >
  Deploy an application to AWS CodeDeploy using OIDC authentication.
  Import the aws-cli orb and authenticate using the aws-cli/setup command with a valid role-arn for OIDC authentication.
usage:
  version: 2.1
  orbs:
    aws-code-deploy: circleci/aws-code-deploy@4.0
    # Importing aws-cli orb is required for OIDC authentication
    aws-cli: circleci/aws-cli@4.0

  workflows:
    deploy_application:
      jobs:
        - aws-code-deploy/deploy:
            auth:
              # Add authentication step with OIDC using aws-cli/setup command
              - aws-cli/setup:
                  profile: "OIDC-USER"
                  role-arn: "arn:aws:iam::123456789012:role/VALID_OIDC_CODEDEPLOY_ROLE"
            application_name: myApplication
            deployment_group: myDeploymentGroup
            service_role_arn: myDeploymentGroupRoleARN
            bundle_bucket: myApplicationS3Bucket
            bundle_key: myS3BucketKey
            # Must use same profile configured in aws-cli/setup command
            profile: "OIDC-USER"
            # must use valid CircleCI context for OIDC authentication
            context: CircleCI_OIDC_Token
